targets:
  $default:
    builders:
      injectable_generator:injectable_builder:  
        options:  
          auto_register: false 
        generate_for:
          include:
            - lib/**_bloc.dart
            - lib/**_cubit.dart