targets:
  $default:
    builders:
      injectable_generator:injectable_builder:  
        options:  
          auto_register: false 
        generate_for:
          include:
            - lib/app/injection/**.dart
            - lib/data/network/**.dart
            - lib/data/storage/**.dart
            - lib/**_bloc.dart
            - lib/**_cubit.dart