name: supono
description: apply-at-supono
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.3
  in_app_review: ^2.0.10
  injectable: ^2.5.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/l10n/
    - assets/images/onboarding/
    - assets/icons/